version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: fullfilment_db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: fullfilment_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts/create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
      - ./init-scripts/insert-db.sql:/docker-entrypoint-initdb.d/insert-db.sql

volumes:
  postgres_data:
    driver: local